### ISSUE TITLE
marquee div

### ISSUE THREAD

**Issue by rabia-aaziz** [Maria-khurshid/mockup-task#1]
diffrence daikhain apnay or maa'am k mockup k red div ka
![Untitled](https://user-images.githubusercontent.com/39001798/58340746-f9d82700-7e65-11e9-990f-94bb43914c92.png)

![Untitled-1](https://user-images.githubusercontent.com/39001798/58340756-ffce0800-7e65-11e9-9727-7f7058926694.png)

**Comment by Maria-khurshid** [comment]
#1 is resolved
