### ISSUE TITLE
correct the portfolio section

### ISSUE THREAD

**Issue by rabia-aaziz** [Maria-khurshid/mockup-task#4]
icons ki position 320 px pay or background image ki height or width sahi karain

![jhjh](https://user-images.githubusercontent.com/39001798/58342472-e333cf00-7e69-11e9-9603-b62c925c9d8e.PNG)
0
![Capture](https://user-images.githubusercontent.com/39001798/58341744-62c09e80-7e68-11e9-9d34-7b85c9807ccf.PNG)

**Comment by Maria-khurshid** [comment]
#4 is resolved
