### ISSUE TITLE
Tech karo circle section

### ISSUE THREAD

**Issue by rabia-aaziz** [Maria-khurshid/mockup-task#6]
text align center karain

![Capture-3](https://user-images.githubusercontent.com/39001798/58342589-386fe080-7e6a-11e9-950f-8365862ccb27.PNG)
![Capture-5](https://user-images.githubusercontent.com/39001798/58342594-39a10d80-7e6a-11e9-9355-4ed313ff5276.PNG)

**Comment by Maria-khurshid** [comment]
#6 is resolved
