### ISSUE TITLE
Duplicate id 

### ISSUE THREAD

**Issue by rabia-aaziz** [Maria-khurshid/mockup-task#8]
duplicate id use nahi kr saktay hai duplicate class use kr sakhtay hain
https://github.com/Maria-khurshid/mockup-task/blob/db2fcd7e0f918a912a862ef71e684c13e466ad0f/index.html#L127

**Comment by Maria-khurshid** [comment]
#8 issue is resolved

**Comment by rabia-aaziz** [comment]
aapnay solve nahi kiya hai issue
![Capture](https://user-images.githubusercontent.com/39001798/58368139-44a77c80-7f02-11e9-874a-1923fad1d68a.PNG)
